### ISSUE TITLE
师兄你好，又是我，现在前端上线出问题了

### ISSUE THREAD

**Issue by cai1818** [caojen/pgms-frontend#1]
![87292810cff54fb3e94e9580a82c4a7](https://user-images.githubusercontent.com/72693103/198859877-034c55e6-0fc4-4379-b737-a376b91b39ec.png)

**Comment by cai1818** [comment]
请问师兄之前有上线到学校虚拟机上过吗，出现过这个情况吗，

**Comment by cai1818** [comment]
![a335d6cd50a218bca13af01eb82b5b2](https://user-images.githubusercontent.com/72693103/198865710-24c34a15-8f30-4ce7-8c36-623e522f52e6.png)
编译的时候有警告，然后就是警告的这两个文件报错

**Comment by cai1818** [comment]
不是警告的问题了😵

**Comment by caojen** [comment]
警告可以无视

**Comment by caojen** [comment]
外网无法访问是吧

**Comment by caojen** [comment]
> ![87292810cff54fb3e94e9580a82c4a7](https://user-images.githubusercontent.com/72693103/198859877-034c55e6-0fc4-4379-b737-a376b91b39ec.png)

不对啊，你这个js怎么加载出来的是html. 你直接在浏览器里面访问一下这个js路径，看看是什么内容。

**Comment by cai1818** [comment]
都无法访问，因为之前都是npm run serve，没试过build，所以觉得没问题，现在我在本地biuld，结果还是一样，空白，然后报一样的错误

**Comment by caojen** [comment]
![image](https://user-images.githubusercontent.com/43436876/198867832-dc2612fe-0262-4cbe-b6ec-13b828cdc6f4.png)
比如说，这个是github的一个js，打开控制台拿到路径，复制到浏览器里面，直接打开。

**Comment by cai1818** [comment]
![a2f80959f3b3b700433870817bf4d7c](https://user-images.githubusercontent.com/72693103/198867873-1057195d-d92d-4161-9e90-3e54f9ed3cad.png)

**Comment by caojen** [comment]
那就是没有识别到js，按“全部”这个tab，找一下那个chunk-*.js

**Comment by cai1818** [comment]
![54376fc6f3011602a8f8732038508af](https://user-images.githubusercontent.com/72693103/198867906-c17d92cb-545c-45e3-8e28-2f1dfd275a1d.png)

**Comment by cai1818** [comment]
![Uploading fe25a6518b6cd6d1ca61e74a72bb909.png…]()
在api网址下全部只有api和一个icon

**Comment by caojen** [comment]
等一下，我大概懂什么意思了。
我研究一下。

**Comment by cai1818** [comment]
好的

**Comment by caojen** [comment]
我确认一下，web将要部署到 `https://isce.sysu.edu.cn/sx` 这个路径，然后访问的js都访问到了 `http://172.18.178.57:23555/js`吗？

**Comment by cai1818** [comment]
啊不是，https://isce.sysu.edu.cn/sx是上线的，172.18.178.57:23555是我本机测试。但是结果一样，都是空白

**Comment by cai1818** [comment]
因为上线的那个出错就删了，然后现在本机做好再上传，

**Comment by cai1818** [comment]
但是两个出现的问题是一样的

**Comment by caojen** [comment]
你那里本地电脑 能装一下向日葵远程控制吗，我连进去看看。

现在看起来没有开放公网访问。

**Comment by cai1818** [comment]
这个本机，指的是实验室的开发服务器来着，能装吗，能装我就装装看

**Comment by caojen** [comment]
额，就是你自己的电脑。

难道之前你都是在实验室的开发服务器上做开发的吗。如果是，我就找找其他同学连一下，还是尽量不要在实验室机器上做事情了。

**Comment by cai1818** [comment]
是的，因为自己电脑上没空间下载环境了😂

**Comment by caojen** [comment]
那这样吧，你把build好后的 `./dist`目录打包，发我一下。

**Comment by cai1818** [comment]
[dist.zip](https://github.com/caojen/pgms-frontend/files/9895373/dist.zip)

**Comment by caojen** [comment]
看起来没毛病。

这样吧，你把这个dist部署到服务器上面去。我找机会连进去学校内网。

**Comment by cai1818** [comment]
部署好了https://icse.sysu.edu.cn/sx/

**Comment by caojen** [comment]
要不开发机上装一个向日葵远程连接吧，到时候搞完删掉就行了。

**Comment by cai1818** [comment]
下好了，不过不是图形化界面，是命令行的

**Comment by caojen** [comment]
啊这，开发机器是没有图形界面的吗？

**Comment by cai1818** [comment]
坏了，下错了，等会

**Comment by cai1818** [comment]
对，开发机器只有命令行

**Comment by caojen** [comment]
没事，不用了，找到了

**Comment by caojen** [comment]
![image](https://user-images.githubusercontent.com/43436876/198870117-42eabe4a-44d0-4569-8ca7-0614745cb792.png)

**Comment by caojen** [comment]
我有输错吗？

**Comment by cai1818** [comment]
/sx/

**Comment by caojen** [comment]
fine...

**Comment by caojen** [comment]
反向代理用的是caddy？

**Comment by caojen** [comment]
我看看caddy对应的配置

**Comment by cai1818** [comment]
对的

**Comment by cai1818** [comment]
![f07352d0c45617b6f63fb17e2b5b3ee](https://user-images.githubusercontent.com/72693103/198870268-efa2d9db-30d9-472b-be86-cbdd8e97a980.png)
这是Caddyfile

**Comment by cai1818** [comment]
![Uploading 37e2c162f805b69dd84b8d330122fb9.png…]()
这是docker-compose

**Comment by cai1818** [comment]
![37e2c162f805b69dd84b8d330122fb9](https://user-images.githubusercontent.com/72693103/198870299-575f08a7-3722-44c2-b3bd-1e03a4e5dfac.png)

**Comment by caojen** [comment]
现在一步一步来。

首先，在前端项目的 `./vue.config.js` 里面，加上 `publicPath: "/sx"`，具体如下图所示：
![image](https://user-images.githubusercontent.com/43436876/198870371-59ed420f-8eb8-48f9-9cd4-7d7f82e3f6d2.png)

然后重新build，再部署到上面去，我再看看。

**Comment by cai1818** [comment]
是publicPath: "/sx"而不是/sx/哦

**Comment by caojen** [comment]
应该没有区别的。

**Comment by caojen** [comment]
这个服务器是小智在管的吗？

**Comment by cai1818** [comment]
不清楚欸，我是1个月前刚加进实验室的

**Comment by caojen** [comment]
我没用过caddy，但是我感觉这个地方要改一下：
![image](https://user-images.githubusercontent.com/43436876/198870586-9307816f-92fc-48b3-9f7b-456f83502ee5.png)
改成 `root * /forsx/dist`

**Comment by caojen** [comment]
因为访问`/sx/js/a.js`的时候，应该要访问 `/forsx/dist/js/a.js`.我猜的，不一定对。

**Comment by cai1818** [comment]
成功了😭

**Comment by caojen** [comment]
fine，那就试试其他功能可不可以吧

**Comment by cai1818** [comment]
太感谢了，搞了2天了😭

**Comment by cai1818** [comment]
嗯嗯

**Comment by caojen** [comment]
看上去是访问后端接口会有问题，估计是caddy配置的问题，这个我就帮不了忙了，我之前用的是nginx，现在工作之后也是nginx。caddy没怎么用过，需要你自己去stackoverflow了。

**Comment by cai1818** [comment]
嗯嗯，所以主要问题是caddy配置，跟publicPath: "/sx“没什么关系对吗

**Comment by caojen** [comment]
有关。

`publicPath: /sx` 会指定编译之后的js/css文件位置。
如果不指定，就会访问 `https://isce.sysu.edu.cn/js/a.js`，如果指定了，就会访问 `https://isce.sysu.edu.cn/sx/js/a.js`。

之前的双选系统是部署在根目录`/`下的，因此没有配置这个。

**Comment by cai1818** [comment]
哦哦，原来如此，我自己百度publicPath的结果说是调整调用assert位置，以为没关系就没管😂

**Comment by cai1818** [comment]
是基础不扎实了

**Comment by caojen** [comment]
问题不大，一劳永逸的，你这次会了，那下次遇到类似的问题也能大概定位了。

**Comment by cai1818** [comment]
嗯嗯，谢谢师兄，我在测试一会，如果完全没问题，我就关掉issue

**Comment by caojen** [comment]
ok

**Comment by cai1818** [comment]
再次感谢🌹🌹🌹🌹🌹

**Comment by cai1818** [comment]
主要是教务老师明天要求上线，搞得我很急😂

**Comment by caojen** [comment]
是哪个教务老师

**Comment by cai1818** [comment]
李湄老师

**Comment by caojen** [comment]
行吧。你先调一下。

**Comment by cai1818** [comment]
ok，感谢师兄耐心解答🌹🌹🌹🌹
