### ISSUE TITLE
对不起，是我之前太激动，没检查全，现在出现了新的问题

### ISSUE THREAD

**Issue by cai1818** [caojen/pgms-frontend#2]

**Comment by cai1818** [comment]
![a83f89e4e54083ddd280584ab08cf9a](https://user-images.githubusercontent.com/72693103/198877451-52d57763-ba5e-4859-9891-468087dbeba3.png)

**Comment by cai1818** [comment]
![7bdc279db0f7b5791e627d642c9d01b](https://user-images.githubusercontent.com/72693103/198877473-b25cb4bd-f954-47a7-ac13-28facc64ac31.png)
上一张图没截全

**Comment by cai1818** [comment]
![dd8009dc4728c23bcdeecd6937b273f](https://user-images.githubusercontent.com/72693103/198877513-4eabaa40-96ea-453f-8850-9aa934013e19.png)
可以正常登录，管理员功能没问题，学生无法显示头像

**Comment by cai1818** [comment]
![15716d961b39dba8383d9c6dc2d6045](https://user-images.githubusercontent.com/72693103/198877560-17756f4a-cb19-4dd4-a56e-10bdc0e46d5a.png)
![3674ec11387ec57e07939f492e9cda2](https://user-images.githubusercontent.com/72693103/198877564-e8f42d9a-17a4-4dd8-94ea-d190577bcc74.png)
老师无法选择或者取消选择学生，且同样不能显示学生头像

**Comment by cai1818** [comment]
![bedcc33a4baccdb6b8a6b10b4012567](https://user-images.githubusercontent.com/72693103/198877669-dcc8eb41-fe24-4a56-a48f-78fadc8713a2.png)
![bab9c79f38ec51815826ab544866da3](https://user-images.githubusercontent.com/72693103/198877686-fee1b190-9668-4d0c-95cd-85de9f97bb53.png)

**Comment by cai1818** [comment]
报的错都是
![d29e53971397037b75e41a732c03777](https://user-images.githubusercontent.com/72693103/198877935-7a879003-db3e-459f-a11f-3de8a14b19e4.png)

**Comment by cai1818** [comment]
更改后，只有在登陆界面报错和无法导入学生头像了

**Comment by cai1818** [comment]
![f640fec6089795d2b2da5d7b640c13f](https://user-images.githubusercontent.com/72693103/198883072-cf5413fc-4029-4f3b-8ded-5a6a5e14049a.png)
这里显示是超时和空的数据

**Comment by caojen** [comment]
额，我想一下

**Comment by caojen** [comment]
本来无法登录，但是后面又可以登录，这是怎么解决的。

**Comment by caojen** [comment]
文件系统部署了吗？

**Comment by cai1818** [comment]
额，是一直可以登录，但是会报错，但是报错不影响其他功能，部署了

**Comment by cai1818** [comment]
curl http://localhost:9333/dir/assign是有正常回应的

**Comment by caojen** [comment]
给我一下一个可用的`username`和`password`。

**Comment by cai1818** [comment]
jack ，123456

**Comment by cai1818** [comment]
管理员的，教师和学生可以自己设置，学生的密码预设成电话后六位了

**Comment by caojen** [comment]
我暂时没有办法连进去学校网络。

检查一下，登录态获得之后，cookie有没有设置上。
![image](https://user-images.githubusercontent.com/43436876/198956146-4a1e73f9-e036-4083-895a-6b6b0751f387.png)

**Comment by cai1818** [comment]
有的
![4c93973f5a14ab2d667729549ab048e](https://user-images.githubusercontent.com/72693103/198958061-7de4b18d-642f-4cdd-8f0c-76260140e665.png)

**Comment by caojen** [comment]
那试试直接在浏览器里面访问  `/api/user/status`

**Comment by cai1818** [comment]
![f149b728c5912a074e0c35fe9ed6ace](https://user-images.githubusercontent.com/72693103/198958349-2f3e1a16-6260-4a52-963c-11bc1d1ca436.png)

**Comment by caojen** [comment]
试试用ip访问呢？

**Comment by cai1818** [comment]
而且输入错密码或者其他数据信息，都返回的empty response

**Comment by cai1818** [comment]
ip访问应该搞不了，因为是虚拟机来着，还是说是前端http。ts改成ip

**Comment by caojen** [comment]
查一下是所有api都报empty response，还是只有一部分报这个错。
如果是所有api都报错，那就看一下后端日志有没有访问记录。

**Comment by cai1818** [comment]
只有这部分

**Comment by caojen** [comment]
那访问`/api/user/status`的时候，后端有打印对应的日志吗？

**Comment by cai1818** [comment]
docker里怎么看日志呢

**Comment by caojen** [comment]
`docker logs -f {容器id或容器名字}`

容器id或名字通过`docker ps -a`查看

**Comment by cai1818** [comment]
![35423688fe91ea5c3bdadef43fc4b65](https://user-images.githubusercontent.com/72693103/198959708-10875bcf-479d-4cbe-916a-da8b35ce499d.png)
下面login是我输入错误的密码

**Comment by caojen** [comment]
`docker inspect {容器id或名字}`

我看看输出结果。

**Comment by cai1818** [comment]
![7D5BTPP)CO{I{PDO3 3J_M6](https://user-images.githubusercontent.com/72693103/198960741-e9148095-a3f8-45e8-9fab-55e4d89fbed9.png)
![()OP_TQJZ$P8@7N3SRJ}ZA](https://user-images.githubusercontent.com/72693103/198960746-265eb6ab-8793-4a7a-b269-e681a0df0180.png)

**Comment by caojen** [comment]
看上去好像没问题。

试一下`curl http://127.0.0.1:23444/user/status`

**Comment by cai1818** [comment]
![f9b8c74c7b9b73e13e4c973339b56e8](https://user-images.githubusercontent.com/72693103/198961630-bf88c50e-036a-4f1f-ae2f-efcca76fd111.png)

**Comment by caojen** [comment]
那就 `curl -H "cookie: token={token}" http://127.0.0.1:23444/user/status`

把`{token}`用浏览器里面的那个cookie的`token`替换。

**Comment by cai1818** [comment]
![81e7d39c91648b12dcfb23c6a55fd1d](https://user-images.githubusercontent.com/72693103/198962151-2fd96ea3-c755-4344-8a3b-d4ed27c8c54a.png)

**Comment by caojen** [comment]
不需要添加中括号。

**Comment by cai1818** [comment]
![63e1df9abd01b8e24800680c5870254](https://user-images.githubusercontent.com/72693103/198966265-60a327eb-8dbc-4069-9a72-5743535c0438.png)

**Comment by caojen** [comment]
输错了吧，`status`写成`s`了

**Comment by cai1818** [comment]
![6f852234c7e608cfb58eb756237239d](https://user-images.githubusercontent.com/72693103/198966811-6716fac5-c0f1-4089-9638-774be5526ee7.png)
bu'a'ho不好意思😳

**Comment by cai1818** [comment]
等下，有个引号

**Comment by cai1818** [comment]
![e2c835fd1ad02584367b5d8aa54826f](https://user-images.githubusercontent.com/72693103/198967170-d494f916-0e37-43e0-b600-9dfcc909f179.png)就这样卡住

**Comment by caojen** [comment]
![image](https://user-images.githubusercontent.com/43436876/198967270-8b94dc4c-427e-40b1-b124-5f6ce5bbb46d.png)
把这个引号去掉。

**Comment by cai1818** [comment]
![4c2f36af82a94134e0386cdf65c3180](https://user-images.githubusercontent.com/72693103/198967459-6e84171e-eea4-4903-b9ba-8b36a5ab266d.png)

**Comment by caojen** [comment]
连进去数据库看看 `token` 这个表里面的内容

`select * from token;`

**Comment by cai1818** [comment]
![8b11eaf194866c7bdad39d1b7c21df2](https://user-images.githubusercontent.com/72693103/198967931-1762373e-1f9c-4cce-a0f3-fd8f1fdd77ef.png)

**Comment by caojen** [comment]
啊这，写数据库的时候没有写进去，还是说你已经退出登录了？

**Comment by cai1818** [comment]
退出的登录

**Comment by caojen** [comment]
不能退出，你现在重登，然后拿到新的cookie，再试一下这个。

> 那就 `curl -H "cookie: token={token}" http://127.0.0.1:23444/user/status`
> 
> 把`{token}`用浏览器里面的那个cookie的`token`替换。

**Comment by cai1818** [comment]
![13d06c3a2e5eeacf526757ffe5c6b24](https://user-images.githubusercontent.com/72693103/198968445-d3515d1b-0c78-4d33-b56d-cff999d20cd5.png)
登录有数据

**Comment by caojen** [comment]
理论上来说那 `/user/status` 接口就没问题。

**Comment by cai1818** [comment]
![68c9a903a6775b81246c78baab19aaa](https://user-images.githubusercontent.com/72693103/198968617-49a0879d-180a-40f2-8293-ed51fda75cd8.png)

**Comment by cai1818** [comment]
因为只有登陆界面会报错，剩下一切正常，很奇怪

**Comment by caojen** [comment]
登陆界面报错是指，没有登录的时候，就会报这个错吗？

**Comment by cai1818** [comment]
![6cc7ffc3a211700edd3ba3cd8fe3399](https://user-images.githubusercontent.com/72693103/198968875-4b08cda6-7658-44c2-a296-657a1ba2f820.png)百度查，都是什么防火墙原因，浏览器版本啥的

**Comment by cai1818** [comment]
对

**Comment by cai1818** [comment]
还有获取学生默认头像时也会报这个错

**Comment by cai1818** [comment]
err_empty _response

**Comment by caojen** [comment]
没有登录的时候报错是正常的。

因为没有登录的时候访问这个接口会报错403，网络中心那个很蠢的防火墙会把403返回值的内容给修改。
我之前是找网络中心那个负责人（已经毕业了）向网络中心申请不修改403内容的。

**Comment by caojen** [comment]
获取默认头像的时候，你同样试试用`curl`在宿主机的`127.0.0.1:23444`访问一下，记得带上`token`作为`cookie`。

**Comment by cai1818** [comment]
正常报错不应该是这个吗
![05d8fccaedc73cb5f4775c11422bb00](https://user-images.githubusercontent.com/72693103/198969512-bdecd4fc-cbf2-48ec-ba22-c8b504c0e35f.png)

**Comment by caojen** [comment]
你走了网络中心（域名是网络中心分发的，证书在他那里），你的数据就不一定是正确的了。

**Comment by caojen** [comment]
你走ip是没问题的。

**Comment by cai1818** [comment]
![2fd7f9463205961ea28761d7e7a90b9](https://user-images.githubusercontent.com/72693103/198970029-b897e16b-f634-4213-b6d5-b71b3e6b098d.png)
如果学生自己上传头像，是可以正常显示的

**Comment by cai1818** [comment]
但是代码不是设置了允许出错，并且不报错吗，是不是我要新设置那个允许报错才能消掉这个报错

**Comment by caojen** [comment]
`select * from file`试试。

**Comment by caojen** [comment]
`select * from file`试试。

**Comment by caojen** [comment]
> 但是代码不是设置了允许出错，并且不报错吗，是不是我要新设置那个允许报错才能消掉这个报错

允许出错是指？

**Comment by cai1818** [comment]
![58435fdcf4f29b3ee13447e6f067023](https://user-images.githubusercontent.com/72693103/198970559-d683dc8a-232b-458a-8079-9d804fdef0cf.jpg)


> > 但是代码不是设置了允许出错，并且不报错吗，是不是我要新设置那个允许报错才能消掉这个报错
> 
> 允许出错是指？

**Comment by cai1818** [comment]
![4f575c477be11a0d1affb2e06874f9c](https://user-images.githubusercontent.com/72693103/198970659-41977f50-1987-49b1-a42d-d213bf54463d.png)

**Comment by cai1818** [comment]
![b5c89d91cded924d979d5ae1a4f4703](https://user-images.githubusercontent.com/72693103/198970742-ee918332-73ed-4497-a0c3-a218347dc099.png)

**Comment by caojen** [comment]
确实有点奇怪。

在这个地方把那个url打印出来看看。

![image](https://user-images.githubusercontent.com/43436876/198971700-4a9bb61c-6347-476c-a14d-8e80adc8dab0.png)

**Comment by caojen** [comment]
我知道了，应该是caddy没有把host带给后端。（但我不清楚caddy是怎么把host带给后端的）

一个简单的方法是，将下面这个函数改一下：
```ts
export default function allowFailure (url: string): boolean {
  return allowApis.map((url) => url.endsWith(url)).some((v) => v)
}
```

**Comment by caojen** [comment]
应该caddy的问题，没有把host带给后端服务，导致`substring`拿出来的内容是错的。

一个简单的方法是，将这个函数改一下：
```ts
export default function allowFailure (url: string): boolean {
  return allowApis.map((_url) => _url.endsWith(url)).some((v) => v)
}
```

**Comment by caojen** [comment]
好像会有点问题，我改一下。

**Comment by cai1818** [comment]
![30b80f649ba4fc8aaf9063be7e3812b](https://user-images.githubusercontent.com/72693103/198974037-dbb698d0-4b85-459c-9e8f-2d16c62a6746.png)
😂

**Comment by caojen** [comment]
改成这样，两个地方。
```ts
export default function allowFailure (url: string): boolean {
  return allowApis.map((_url) => url.endsWith(_url)).some((v) => v)
}
```

```ts
if (!allowFailure(err.request.responseURL)) {
  // ...
}
```

**Comment by caojen** [comment]
控制台报错是正常的，主要是让那个ui的通知不弹出。

**Comment by cai1818** [comment]
还是有

**Comment by cai1818** [comment]
啊，没了，我忘记刷新了

**Comment by cai1818** [comment]
但是这样会吞掉所有错误，因为网络中心把错误都改成一个类型

**Comment by cai1818** [comment]
密码错误也吞掉了

**Comment by cai1818** [comment]
是不是只能这么处理呢

> 没有登录的时候报错是正常的。
> 
> 因为没有登录的时候访问这个接口会报错403，网络中心那个很蠢的防火墙会把403返回值的内容给修改。 我之前是找网络中心那个负责人（已经毕业了）向网络中心申请不修改403内容的。

**Comment by cai1818** [comment]
如果我把HttpException的响应值从403改到200，可行吗

**Comment by caojen** [comment]
我得看看这个东西是什么。
```ts
if (!allowFailure(err.request.responseURL)) {
  console.log(err.request.responseURL)
  // ...
}
```

**Comment by caojen** [comment]
200算是登录成功，你可以试试改成406.

**Comment by cai1818** [comment]
406也吞
![b7d0e71e733c1acf4c5c5ce59542561](https://user-images.githubusercontent.com/72693103/198977634-e07f95eb-c2d1-4af6-a834-b3d4cfa7f439.png)

**Comment by caojen** [comment]
那就没辙了。

![image](https://user-images.githubusercontent.com/43436876/198977849-756be2dc-56c8-4eeb-b4af-95b5f8d1aba4.png)

在这里加个`?`规避掉第二条错误。

**Comment by caojen** [comment]
要不申请一下吧，开放一下4xx错误，不然挺难搞的。

**Comment by cai1818** [comment]
加问号会编译失败
![2be5e2ddeafcb638fadd572c8299044](https://user-images.githubusercontent.com/72693103/198978505-7ba2669d-1ce3-4be5-a2d1-71e0632c4aca.png)

**Comment by cai1818** [comment]
郑贵峰老师建议返回200，正常回复json串，前端解释json串，json串里含失败信息

**Comment by caojen** [comment]
额，这种非restful的解决方式，你得前后端都改一大堆内容了。建议不要。

**Comment by cai1818** [comment]
我觉得挺不现实，毕竟一改就该一大堆

**Comment by cai1818** [comment]
对

**Comment by caojen** [comment]
> 那就没辙了。
> 
> ![image](https://user-images.githubusercontent.com/43436876/198977849-756be2dc-56c8-4eeb-b4af-95b5f8d1aba4.png)
> 
> 在这里加个`?`规避掉第二条错误。

那就先把这个回撤吧。

**Comment by caojen** [comment]
拿你试一下，这样：
```
curl -H "cookie: token={token}" http://127.0.0.1:23444/admin/bichoice/settings
```

> 406也吞 ![b7d0e71e733c1acf4c5c5ce59542561](https://user-images.githubusercontent.com/72693103/198977634-e07f95eb-c2d1-4af6-a834-b3d4cfa7f439.png)

**Comment by cai1818** [comment]
![c425b40d094f320681df7172d71b05b](https://user-images.githubusercontent.com/72693103/198980524-59a142ef-5e61-4d26-b059-37141fbce33f.png)

**Comment by caojen** [comment]
这个token是双选管理员的token？

```sql
select * from token;
select * from user;
select * from admin;
```

**Comment by cai1818** [comment]
token表只有一个啊，所有人共享一个表把

**Comment by caojen** [comment]
是，你执行一下上面的sql看看。

**Comment by cai1818** [comment]
![d4558c87682aa22285fce02e327f2e2](https://user-images.githubusercontent.com/72693103/198981417-5fb033fc-d364-4228-a211-70d2dccf0582.png)

**Comment by caojen** [comment]
额，你这token怎么不在表里面

> ![c425b40d094f320681df7172d71b05b](https://user-images.githubusercontent.com/72693103/198980524-59a142ef-5e61-4d26-b059-37141fbce33f.png)

**Comment by caojen** [comment]
token不在token表里面，等于没有登录态。

**Comment by cai1818** [comment]
因为我刚测试的是登录已经登录的账号

**Comment by cai1818** [comment]
代码里不是会把这个错误返回406吗

**Comment by cai1818** [comment]
![d88f0becfd1ed5769c4f0f279dc40d2](https://user-images.githubusercontent.com/72693103/198981886-429b5aa1-fd7f-4d6c-a65a-e079a1724cbe.png)
bai'yan😭

**Comment by caojen** [comment]
其实就是懒得申请而已（

**Comment by caojen** [comment]
没有登录态的时候访问登录接口会返回403.

**Comment by caojen** [comment]
> 额，你这token怎么不在表里面
> 
> > ![c425b40d094f320681df7172d71b05b](https://user-images.githubusercontent.com/72693103/198980524-59a142ef-5e61-4d26-b059-37141fbce33f.png)

试一下用有效的token去curl

**Comment by cai1818** [comment]
![16a7bfe070799835845c67f4e86c2dc](https://user-images.githubusercontent.com/72693103/198982566-910aedc3-f216-4735-91d7-0e4397e2b3ec.png)

**Comment by caojen** [comment]
那其实是没问题的

**Comment by cai1818** [comment]
能改成406的意思吗

**Comment by cai1818** [comment]
现在就能少改点就少改点了

**Comment by caojen** [comment]
不能改，我只是说接口没有问题。

现在的问题是不是，错误提示会有问题

**Comment by caojen** [comment]
而且改了406也会被吞，不能解决这个错误提示的问题。

**Comment by cai1818** [comment]
嗯，但是老师不让改网络中心的，只能自己解决了

**Comment by cai1818** [comment]
他现在极力推荐改成200，

**Comment by caojen** [comment]
那我是不是可以理解成，除了这个错误提示之外，其他接口在正常使用的情况下都没有问题。

**Comment by cai1818** [comment]
对

**Comment by caojen** [comment]
改成500试试？

**Comment by cai1818** [comment]
我先看看原来代码有没有得直接看看会不会吞，不然虚拟机上现在连不了开发机器，传后端会很麻烦

**Comment by caojen** [comment]
那你把mysql暂停了

全部访问数据库的接口都会报500

**Comment by cai1818** [comment]
![8b2a43ee89db8da185076521b7884d8](https://user-images.githubusercontent.com/72693103/198984796-b292c944-fb51-4395-8ac6-e0c89d4408ed.png)
ee

**Comment by caojen** [comment]
![image](https://user-images.githubusercontent.com/43436876/198985427-7dd20549-289d-4c80-9067-fbd2452c4347.png)
把那句话改成这样试试？

**Comment by caojen** [comment]
![image](https://user-images.githubusercontent.com/43436876/198985885-d02ea4e6-6655-4268-9a38-0a77a9d6f660.png)
这样，加个括号避免lint错误。

**Comment by cai1818** [comment]
![aae22ba4084a5e5fef6d8f88b7032a4](https://user-images.githubusercontent.com/72693103/198988406-f65e80a1-e6cc-4e48-9767-2a0f561c5fdb.png)

**Comment by caojen** [comment]
挺玄乎的，`/user/status`报错的时候应该不会弹窗了是吧。

那就得看看其他接口报错的时候，显示这个统一的弹窗能不能接受了。

**Comment by cai1818** [comment]
现在老师只要求，错误密码有弹窗，剩下错误都不弹窗了

**Comment by cai1818** [comment]
现在我自己偷偷去申请了😄，就行了，谢谢师兄
